name: Inference Workflow

on:
  push:
    branches: [inference]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install -r requirements.txt
      - run: pytest tests/

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install -r requirements.txt
      - run: python src/train.py
      - uses: actions/upload-artifact@v3
        with:
          name: model
          path: model_train.pkl

  inference:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v3
        with:
          name: model
      - run: python src/inference.py
