name: Train Model

on:
  push:
    branches: [classification]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Training Script
      run: python src/train.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v3
      with:
        name: model
        path: model_train.pkl
name: Train Pipeline
on:
  push:
    branches:
      - classification_branch
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run training
        run: python src/train.py
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model_train.pkl 
